# Generated by Django 4.2.11 on 2025-02-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
    ]
