# Generated by Django 4.2.11 on 2025-02-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anything_apps', '0003_remove_apppage_css_content_app_css_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datastore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datastore',
            name='table_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastore',
            name='key',
            field=models.CharField(help_text='Column name in the abstract table', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='datastore',
            unique_together={('app', 'table_name')},
        ),
    ]
