# Generated by Django 4.2.11 on 2025-02-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anything_apps', '0004_alter_datastore_unique_together_datastore_table_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datastore',
            unique_together={('app', 'id')},
        ),
    ]
